#!/usr/bin/env python3
"""Generates tests/reference/reference_vectors.h — the independent golden leg
of the M3 correctness battery (PLAN.md section 6.2).

The input is deterministic xorshift noise quantized to float32. For each
direction x profile, the expected output is computed by scipy.signal.upfirdn
(a polyphase engine we did not write) in float64, using coefficients from the
same published Kaiser math as tap::dsp::design_prototype plus RatioTap's
per-branch DC normalization (tap/ratio/design.h), then cast to float32.

The streaming converter is zero-primed and causal, so its output must equal
upfirdn's from sample 0 — transient included — within float32 rounding: the
C++ engine stores float32 coefficients and accumulates in double, while this
reference keeps float64 coefficients, so the comparison tolerance in
tests/test_converter.cpp (3e-5 absolute at 0.9 peak) is the float32
coefficient-quantization floor, about -90 dB.

Run from the repo root:  python3 tools/reference/make_reference_vectors.py
Re-run only when the design math changes; commit the regenerated header.
"""
import numpy as np
from scipy import signal
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]


def kaiser_beta(atten_db):
    if atten_db > 50.0:
        return 0.1102 * (atten_db - 8.7)
    if atten_db > 21.0:
        return 0.5842 * (atten_db - 21.0) ** 0.4 + 0.07886 * (atten_db - 21.0)
    return 0.0


def design(L, taps, cutoff_norm, beta):
    n = L * taps
    i = np.arange(n)
    center = 0.5 * (n - 1)
    t = (i - center) / L
    u = (i - center) / center
    w = np.i0(beta * np.sqrt(np.maximum(0.0, 1.0 - u * u))) / np.i0(beta)
    h = cutoff_norm * np.sinc(cutoff_norm * t) * w
    h *= L / h.sum()
    branch = h.reshape(taps, L).sum(axis=0)
    return (h.reshape(taps, L) / branch).reshape(-1)


def xorshift_f32(count, seed):
    s = np.uint32(seed)
    out = np.empty(count, np.float32)
    for i in range(count):
        s ^= np.uint32((int(s) << 13) & 0xFFFFFFFF)
        s ^= np.uint32(int(s) >> 17)
        s ^= np.uint32((int(s) << 5) & 0xFFFFFFFF)
        out[i] = np.float32((int(s) % 65536 - 32768) / 65536.0) * np.float32(0.9)
    return out


CASES = [  # tag, L, M, fs_in, pass_hz, stop_hz, atten, taps
    ("down_economy",     147, 160, 48000.0, 19000.0, 22050.0,  70.0,  78),
    ("down_transparent", 147, 160, 48000.0, 20000.0, 22050.0, 120.0, 184),
    ("up_economy",       160, 147, 44100.0, 19000.0, 24000.0,  70.0,  44),
    ("up_transparent",   160, 147, 44100.0, 20000.0, 24000.0, 120.0,  96),
]

N_IN = 1000
x = xorshift_f32(N_IN, 0x2545F491)


def fmt(arr, per_line=8):
    lines = []
    for i in range(0, len(arr), per_line):
        lines.append("    " + ", ".join(f"{v:.9e}f" for v in arr[i:i + per_line]) + ",")
    return "\n".join(lines)


out = []
out.append("// Generated by tools/reference/make_reference_vectors.py — DO NOT EDIT.")
out.append("// Independent golden reference: scipy.signal.upfirdn (float64) over the")
out.append("// per-branch-normalized Kaiser designs, cast to float32. See that script")
out.append("// for provenance and the tolerance argument.")
out.append("// SPDX-License-Identifier: MIT")
out.append("// Copyright 2026 Timothy Place and the RatioTap contributors.")
out.append("// NOLINTBEGIN(readability-identifier-naming)")
out.append("#pragma once")
out.append("")
out.append("#include <array>")
out.append("")
out.append("namespace ratio_ref {")
out.append("")
out.append(f"inline constexpr std::array<float, {N_IN}> k_input = {{")
out.append(fmt(x))
out.append("};")
out.append("")

for tag, L, M, fs, pas, stop, atten, taps in CASES:
    h = design(L, taps, (pas + stop) / fs, kaiser_beta(atten))
    y = signal.upfirdn(h, x.astype(np.float64), up=L, down=M)
    # The streaming engine only emits outputs whose full input window has
    # arrived: newest input for output n is x[floor(nM/L)], so keep outputs
    # with floor(nM/L) < N_IN. upfirdn's longer tail is the flush territory.
    n_stream = 0
    while (n_stream * M) // L < N_IN:
        n_stream += 1
    y = y[:n_stream].astype(np.float32)
    out.append(f"inline constexpr std::array<float, {len(y)}> k_{tag} = {{")
    out.append(fmt(y))
    out.append("};")
    out.append("")

out.append("} // namespace ratio_ref")
out.append("// NOLINTEND(readability-identifier-naming)")

dest = ROOT / "tests" / "reference" / "reference_vectors.h"
dest.parent.mkdir(parents=True, exist_ok=True)
dest.write_text("\n".join(out) + "\n")
print(f"wrote {dest} ({dest.stat().st_size / 1024:.0f} KiB)")
