#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright 2026 Timothy Place and the SampleRateTap contributors
"""Generates tests/reference/reference_vectors.h — the independent golden leg
of the rational engine's M3 battery (PLAN.md section 5, leg 1).

The input is deterministic xorshift noise quantized to float32 (bridge's
generator's draw, a different seed). For each single-stage ratio of the
vocabulary at the economy profile (and the by-2 pair at transparent), the
expected output is scipy.signal.upfirdn(h, x, up=L, down=M) in float64 over
the stage's table — the L-th-band design from the same published math as
tap::dsp::design_nyquist (DspTap nyquist.h: Kaiser-windowed sinc with cutoff
pi / B, the centre exactly 1, the structural zeros exactly 0, every B-branch
at DC gain 1) with the stage's gain rule (stage.h): going up the table is
the design; a decimator's is h / M; a mixed ratio going down has each of its
L phases normalized to sum 1. Cast to float32.

The streaming stage is zero-primed and causal, so its output equals
upfirdn's from sample 0 — transient included — within float32 rounding: the
C++ stores float32 coefficients and accumulates in double, this reference
keeps float64 coefficients, so the comparison tolerance in
tests/test_stage.cpp (3e-5 absolute at 0.9 peak, bridge's) is the float32
coefficient-quantization floor, about -90 dB; the double engine is compared
at the float32 cast's own floor.

Run from the engine root:  python3 tools/reference/make_reference_vectors.py
Re-run only when the design or the gain rule changes; commit the header.
"""
import pathlib

import numpy as np
from scipy import signal

ROOT = pathlib.Path(__file__).resolve().parents[2]


def kaiser_beta(atten_db):
    if atten_db > 50.0:
        return 0.1102 * (atten_db - 8.7)
    if atten_db > 21.0:
        return 0.5842 * (atten_db - 21.0) ** 0.4 + 0.07886 * (atten_db - 21.0)
    return 0.0


def design_nyquist(band, m, beta):
    # Mirrors tap::dsp::design_nyquist (as notebooks/design_spike.ipynb).
    n = 2 * m * band - 1
    c = (n - 1) // 2
    i = np.arange(n)
    u = (i - c) / c
    w = np.i0(beta * np.sqrt(np.maximum(0.0, 1.0 - u * u))) / np.i0(beta)
    h = np.sinc((i - c) / band) / band * w
    h[c] = 1.0
    h[(i != c) & ((i - c) % band == 0)] = 0.0
    for j in range(band):
        if j == c % band:
            continue
        sel = (i % band) == j
        h[sel] /= h[sel].sum()
    return h


def stage_table(L, M, m, beta):
    # stage.h's gain rule over the band-B design.
    B = max(L, M)
    h = design_nyquist(B, m, beta)
    if L == 1:
        return h / M
    if M > L:
        for p in range(L):
            h[p::L] /= h[p::L].sum()
    return h


def xorshift_f32(count, seed):
    s = np.uint32(seed)
    out = np.empty(count, np.float32)
    for i in range(count):
        s ^= np.uint32((int(s) << 13) & 0xFFFFFFFF)
        s ^= np.uint32(int(s) >> 17)
        s ^= np.uint32((int(s) << 5) & 0xFFFFFFFF)
        out[i] = np.float32((int(s) % 65536 - 32768) / 65536.0) * np.float32(0.9)
    return out


# The pinned taps per branch (design.h's table): economy and transparent.
PINS = {"economy": {2: 11, 3: 11, 4: 11, 6: 12, 8: 12}, "transparent": {2: 31, 3: 25, 4: 25, 6: 25, 8: 25}}
ATTEN = {"economy": 70.0, "transparent": 120.0}

CASES = [  # tag, L, M, profile
    ("up_2", 2, 1, "economy"), ("down_2", 1, 2, "economy"),
    ("up_3", 3, 1, "economy"), ("down_3", 1, 3, "economy"),
    ("up_6", 6, 1, "economy"), ("down_6", 1, 6, "economy"),
    ("up_8", 8, 1, "economy"), ("down_8", 1, 8, "economy"),
    ("ratio_3_2", 3, 2, "economy"), ("ratio_2_3", 2, 3, "economy"),
    ("ratio_4_3", 4, 3, "economy"), ("ratio_3_4", 3, 4, "economy"),
    ("ratio_8_3", 8, 3, "economy"), ("ratio_3_8", 3, 8, "economy"),
    ("up_2_transparent", 2, 1, "transparent"), ("down_2_transparent", 1, 2, "transparent"),
]

N_IN = 480  # divisible by every M of the vocabulary: whole superblocks
x = xorshift_f32(N_IN, 0x7A3D9E15)


def fmt(arr, per_line=8):
    return "\n".join("    " + ", ".join(f"{v:.9e}f" for v in arr[i:i + per_line]) + ","
                     for i in range(0, len(arr), per_line))


out = []
out.append("// Generated by tools/reference/make_reference_vectors.py — DO NOT EDIT.")
out.append("// Independent golden reference: scipy.signal.upfirdn (float64) over the")
out.append("// stages' L-th-band tables, cast to float32. See that script for the")
out.append("// provenance and the tolerance argument.")
out.append("// SPDX-License-Identifier: MIT")
out.append("// Copyright 2026 Timothy Place and the SampleRateTap contributors")
out.append("// NOLINTBEGIN(readability-identifier-naming)")
out.append("#pragma once")
out.append("")
out.append("#include <array>")
out.append("")
out.append("namespace rational_ref {")
out.append("")
out.append(f"inline constexpr std::array<float, {N_IN}> k_input = {{")
out.append(fmt(x))
out.append("};")
out.append("")

for tag, L, M, prof in CASES:
    B = max(L, M)
    h = stage_table(L, M, PINS[prof][B], kaiser_beta(ATTEN[prof]))
    y = signal.upfirdn(h, x.astype(np.float64), up=L, down=M)
    # Outputs whose newest input, x[floor(nM/L)], has arrived; the rest is
    # the flush territory.
    n_stream = 0
    while (n_stream * M) // L < N_IN:
        n_stream += 1
    y = y[:n_stream].astype(np.float32)
    name = tag if prof == "economy" and not tag.endswith("transparent") else tag
    out.append(f"inline constexpr std::array<float, {len(y)}> k_{name} = {{")
    out.append(fmt(y))
    out.append("};")
    out.append("")

out.append("} // namespace rational_ref")
out.append("// NOLINTEND(readability-identifier-naming)")

dest = ROOT / "tests" / "reference" / "reference_vectors.h"
dest.write_text("\n".join(out) + "\n")
print(f"wrote {dest} ({dest.stat().st_size / 1024:.0f} KiB)")
