# 4.2 check 3: an engine's public headers name no srt/, no sibling
# tap/sr/<other>/, no ../ and no sibling __has_include.
#   cmake -DENGINE=<engine> -DINCLUDE=<dir> "-DOTHER=<sibling>[;<sibling>]" -P this
if(NOT DEFINED INCLUDE OR NOT DEFINED OTHER OR NOT DEFINED ENGINE)
    message(FATAL_ERROR "ENGINE, INCLUDE and OTHER are required")
endif()
file(GLOB_RECURSE _files ${INCLUDE}/*.h)
if(NOT _files)
    message(FATAL_ERROR "no headers under ${INCLUDE}: an empty check must not pass")
endif()
set(_bad)
set(_lines_checked 0)
foreach(_f IN LISTS _files)
    file(STRINGS ${_f} _lines REGEX "#[ \t]*include|__has_include")
    foreach(_l IN LISTS _lines)
        math(EXPR _lines_checked "${_lines_checked} + 1")
        set(_names_sibling FALSE)
        foreach(_o IN LISTS OTHER)
            if(_l MATCHES "tap/sr/${_o}/")
                set(_names_sibling TRUE)
            endif()
        endforeach()
        if(_l MATCHES "[\"<]srt/" OR _names_sibling OR _l MATCHES "\\.\\./"
           OR (_l MATCHES "__has_include" AND _l MATCHES "tap/sr/"))
            file(RELATIVE_PATH _rel ${INCLUDE} ${_f})
            list(APPEND _bad "${_rel}: ${_l}")
        endif()
    endforeach()
endforeach()
if(_bad)
    list(JOIN _bad "\n  " _bad)
    message(FATAL_ERROR "tap::sr::${ENGINE} public headers reach outside the engine:\n  ${_bad}")
endif()
list(LENGTH _files _n)
message(STATUS "tap::sr::${ENGINE}: ${_lines_checked} include line(s) in ${_n} header(s) stay in the engine")
